"""message 4

Revision ID: 12a7d8de9e7b
Revises: 486d7ae76642
Create Date: 2026-01-07 22:12:57.460520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '12a7d8de9e7b'
down_revision: Union[str, Sequence[str], None] = '486d7ae76642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chapterquestion_question_text'), 'chapterquestion', ['question_text'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chapterquestion_question_text'), table_name='chapterquestion')
    # ### end Alembic commands ###
