"""message 2

Revision ID: 3a7638d63c90
Revises: c30ddcaca803
Create Date: 2026-01-07 22:03:14.252064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '3a7638d63c90'
down_revision: Union[str, Sequence[str], None] = 'c30ddcaca803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapterquestion', 'question_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapterquestion', sa.Column('question_text', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
