"""message 3

Revision ID: 486d7ae76642
Revises: 3a7638d63c90
Create Date: 2026-01-07 22:03:44.264947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '486d7ae76642'
down_revision: Union[str, Sequence[str], None] = '3a7638d63c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapterquestion', sa.Column('question_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapterquestion', 'question_text')
    # ### end Alembic commands ###
