"""message2

Revision ID: 9f01dc317ed5
Revises: a3dba355615d
Create Date: 2026-01-15 19:44:12.840696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '9f01dc317ed5'
down_revision: Union[str, Sequence[str], None] = 'a3dba355615d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userresponse', 'feedback_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('userresponse', 'feedback_grade',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userresponse', 'feedback_grade',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('userresponse', 'feedback_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
