"""message

Revision ID: ad31ba263f68
Revises: 93411d87f22f
Create Date: 2026-01-15 19:58:11.791434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'ad31ba263f68'
down_revision: Union[str, Sequence[str], None] = '93411d87f22f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('userresponse_question_id_fkey'), 'userresponse', type_='foreignkey')
    op.drop_constraint(op.f('userresponse_user_id_fkey'), 'userresponse', type_='foreignkey')
    op.create_foreign_key(None, 'userresponse', 'chapterquestion', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'userresponse', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userresponse', type_='foreignkey')
    op.drop_constraint(None, 'userresponse', type_='foreignkey')
    op.create_foreign_key(op.f('userresponse_user_id_fkey'), 'userresponse', 'user', ['user_id'], ['id'])
    op.create_foreign_key(op.f('userresponse_question_id_fkey'), 'userresponse', 'chapterquestion', ['question_id'], ['id'])
    # ### end Alembic commands ###
